apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels: { app.kubernetes.io/part-of: healthtrack }
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels: { app.kubernetes.io/part-of: healthtrack }
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels: { app.kubernetes.io/part-of: healthtrack }
