apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: healthtrack
spec:
  capacity:
    storage: 1Gi
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: manual
  hostPath:
    path: /data/healthtrack-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: database
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: healthtrack
spec:
  storageClassName: manual
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: database
      app.kubernetes.io/part-of: healthtrack
