apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: database
  labels:
    app.kubernetes.io/name: database-migrate
    app.kubernetes.io/part-of: healthtrack
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-migrate
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-init
          mountPath: /migrations
          readOnly: true
        command: ["sh","-lc"]
        args:
        - |
          echo "Esperando DB ficar pronto...";
          until pg_isready -h db-svc.database.svc.cluster.local -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do
            sleep 2;
          done
          echo "Aplicando migrações idempotentes...";
          for f in /migrations/*.sql; do
            [ -f "$f" ] || continue;
            echo "-> $f";
            psql -h db-svc.database.svc.cluster.local -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB" -f "$f" || exit 1;
          done
          echo "Migrações concluídas.";
      volumes:
      - name: db-init
        configMap:
          name: db-init-sql
