kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: healthtrack
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30090
    hostPort: 30090
    protocol: TCP
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
