apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_HOST: "db-svc.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "healthtrack"
  DB_USER: "healthtrack"
  DB_PASSWORD: "secret"
